[workspace]
members = [
  "numbas",
  "rumbas",
  "rumbas_support",
  "rumbas_support_derive",
]

[patch.crates-io]
comparable = { git = "https://github.com/jhoobergs/comparable.git" }
serde = { git = "https://github.com/jhoobergs/serde.git"}

