pub struct NumbasDefaults {
    pub navigation_reverse: bool,
    pub navigation_browsing_enabled: bool,
    pub navigation_allow_steps: bool,
    pub navigation_prevent_leaving: bool,
    pub navigation_show_results_page: crate::exam::ExamShowResultsPage,
    pub navigation_show_names_of_question_groups: bool,
    pub navigation_start_password: String,
    pub navigation_on_leave: crate::exam::ExamLeaveAction,
    pub question_navigation_prevent_leaving: bool,
    pub basic_settings_show_student_name: bool,
    pub basic_settings_allow_printing: bool,
    pub feedback_review_show_score: bool,
    pub feedback_review_show_feedback: bool,
    pub feedback_review_show_expected_answer: bool,
    pub feedback_review_show_advice: bool,
    pub builtin_constants_e: bool,
    pub builtin_constants_i: bool,
    pub builtin_constants_pi: bool,
    pub part_common_marks: usize,
    pub part_common_use_custom_name: bool,
    pub part_common_steps_penalty: usize,
    pub part_common_enable_minimum_marks: bool,
    pub part_common_minimum_marks: usize,
    pub part_common_show_feedback_icon: bool,
    pub part_common_adaptive_marking_penalty: usize,
    pub part_common_extend_base_marking_algorithm: bool,
    pub number_entry_correct_answer_style: crate::exam::AnswerStyle,
    pub length_restriction_length: usize,
    pub number_entry_fractions_must_be_reduced: bool,
    pub number_entry_partial_credit_if_fraction_not_reduced: crate::exam::Primitive,
    pub number_entry_hint_fraction: bool,

    pub choose_one_has_to_select_option: bool,
    pub choose_one_show_cell_answer_state: bool,
    pub gapfill_sort_answers: bool,
    pub match_answers_with_items_min_answers: usize,
    pub choose_multiple_min_answers: usize,

    pub jme_single_letter_variables: bool,
    pub jme_allow_unknown_functions: bool,
    pub jme_implicit_function_composition: bool,
    pub jme_simplification_simplify_basic: bool,
    pub jme_simplification_simplify_unit_factor: bool,
    pub jme_simplification_simplify_unit_power: bool,
    pub jme_simplification_simplify_unit_denominator: bool,
    pub jme_simplification_simplify_zero_factor: bool,
    pub jme_simplification_simplify_zero_term: bool,
    pub jme_simplification_simplify_zero_power: bool,
    pub jme_simplification_simplify_zero_base: bool,
    pub jme_simplification_collect_numbers: bool,
    pub jme_simplification_constants_first: bool,
    pub jme_simplification_simplify_sqrt_products: bool,
    pub jme_simplification_simplify_sqrt_division: bool,
    pub jme_simplification_simplify_sqrt_square: bool,
    pub jme_simplification_simplify_other_numbers: bool,
    pub jme_simplification_simplify_no_leading_minus: bool,
    pub jme_simplification_simplify_fractions: bool,
    pub jme_simplification_simplify_trigonometric: bool,
    pub jme_simplification_cancel_terms: bool,
    pub jme_simplification_cancel_factors: bool,
    pub jme_simplification_collect_like_fractions: bool,
    pub jme_simplification_order_canonical: bool,
    pub jme_simplification_use_times_dot: bool,
    pub jme_simplification_expand_brackets: bool,
}

// TODO default values
pub const DEFAULTS: NumbasDefaults = NumbasDefaults {
    navigation_reverse: true,
    navigation_browsing_enabled: true,
    navigation_allow_steps: true,
    navigation_prevent_leaving: true,
    navigation_show_results_page: crate::exam::ExamShowResultsPage::Never,
    navigation_show_names_of_question_groups: true,
    navigation_start_password: String::new(),
    navigation_on_leave: crate::exam::ExamLeaveAction::None {
        message: String::new(),
    },
    question_navigation_prevent_leaving: true,
    basic_settings_show_student_name: true,
    basic_settings_allow_printing: true,
    feedback_review_show_score: true,
    feedback_review_show_feedback: true,
    feedback_review_show_expected_answer: true,
    feedback_review_show_advice: true,
    builtin_constants_e: false,
    builtin_constants_i: false,
    builtin_constants_pi: false,
    part_common_marks: 0,
    part_common_use_custom_name: false,
    part_common_steps_penalty: 0,
    part_common_enable_minimum_marks: true,
    part_common_minimum_marks: 0,
    part_common_show_feedback_icon: true,
    part_common_adaptive_marking_penalty: 0,
    part_common_extend_base_marking_algorithm: true,
    number_entry_correct_answer_style: crate::exam::AnswerStyle::EnglishPlain,
    length_restriction_length: 0,

    choose_one_has_to_select_option: true,
    choose_one_show_cell_answer_state: true,
    gapfill_sort_answers: true,
    match_answers_with_items_min_answers: 0,
    choose_multiple_min_answers: 0,

    number_entry_fractions_must_be_reduced: false,
    number_entry_partial_credit_if_fraction_not_reduced: crate::exam::Primitive::Natural(0),
    number_entry_hint_fraction: true,

    jme_single_letter_variables: false,
    jme_allow_unknown_functions: false,
    jme_implicit_function_composition: false,
    jme_simplification_simplify_basic: true,
    jme_simplification_simplify_unit_factor: true,
    jme_simplification_simplify_unit_power: true,
    jme_simplification_simplify_unit_denominator: true,
    jme_simplification_simplify_zero_factor: true,
    jme_simplification_simplify_zero_term: true,
    jme_simplification_simplify_zero_power: true,
    jme_simplification_simplify_zero_base: true,
    jme_simplification_collect_numbers: true,
    jme_simplification_constants_first: true,
    jme_simplification_simplify_sqrt_products: true,
    jme_simplification_simplify_sqrt_division: true,
    jme_simplification_simplify_sqrt_square: true,
    jme_simplification_simplify_other_numbers: true,
    jme_simplification_simplify_no_leading_minus: true,
    jme_simplification_simplify_fractions: true,
    jme_simplification_simplify_trigonometric: true,
    jme_simplification_cancel_terms: true,
    jme_simplification_cancel_factors: true,
    jme_simplification_collect_like_fractions: true,
    jme_simplification_order_canonical: false,
    jme_simplification_use_times_dot: true,
    jme_simplification_expand_brackets: false,
};
