[package]
name = "rumbas"
version = "0.2.1"
authors = ["Jesse Hoobergs <jesse@hoobergs.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version="1.0.110", features=["derive"]}                                
serde_json = "1.0.53"
serde_yaml = "0.8.13"
numbas = {path="../numbas"}
regex = "1"
clap = {version = "2.33", features = ["yaml"]}
