[package]
name = "rumbas"
version = "0.3.0"
authors = ["Jesse Hoobergs <jesse@hoobergs.be>"]
edition = "2018"

[[bin]]
name = "rumbas"
path = "src/main.rs"

[lib]
name = "rumbas"
path = "src/lib.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version="1.0.110", features=["derive"]}                                
serde_json = "1.0.53"
serde_yaml = "0.8.13"
numbas = {path="../numbas"}
regex = "1"
clap = {version = "2.33", features = ["yaml"]}
