[package]
name = "rumbas"
version = "0.4.1-rc"
authors = ["Jesse Hoobergs <jesse@hoobergs.be>"]
edition = "2018"

[[bin]]
name = "rumbas"
path = "src/main.rs"

[lib]
name = "rumbas"
path = "src/lib.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version="1.0.110", features=["derive"]}                                
serde_json = "1.0.53"
serde_yaml = "0.8.13"
numbas = {path="../numbas"}
regex = "1"
clap = {version = "2.33", features = ["yaml"]}
sanitize-filename = "0.3.0"

log = "0.4"
fern = { version = "0.5", features = ["colored"] }
chrono = "0.4"

enum-display-derive = "0.1.1"

#schemars= "0.8.3"
schemars = { git = "https://github.com/jhoobergs/schemars.git", branch = "tagged-enums-as-if-else" }

paste = "1.0"

rumbas_support = { path="../rumbas_support" }
