name: Rust

on:
  push:
    branches: [master]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check_numbas:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            numbas/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --verbose
        working-directory: numbas
      - name: Run tests
        run: cargo test --verbose
        working-directory: numbas
      - name: Run doc
        run: cargo doc --no-deps
        working-directory: numbas

  check_rumbas:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            numbas/target
            rumbas/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --verbose
        working-directory: rumbas
      - name: Run tests
        run: cargo test --verbose
        working-directory: rumbas
      - name: Run doc
        run: cargo doc --no-deps
        working-directory: rumbas
  check_cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            numbas/target
            rumbas/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install rumbas
        run: cargo install --path .
        working-directory: rumbas
      - name: Clone Numbas
        run: |-
          git clone https://github.com/numbas/Numbas.git ~/NUMBAS
      - name: Run cli-tests
        run: |-
          export NUMBAS_FOLDER=~/NUMBAS
          ./test.sh
        working-directory: cli-tests
  check_todos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            numbas/target
            rumbas/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Add nightly
        run: |-
          rustup install nightly
          rustup +nightly component add rustfmt
        working-directory: rumbas
      - name: Check todo's
        run: cargo +nightly fmt --all -- --check
        working-directory: rumbas
