name: Rust

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check_numbas:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            numbas/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --verbose
        working-directory: numbas
      - name: Run tests
        run: cargo test --verbose
        working-directory: numbas
      - name: Run doc
        run: cargo doc --no-deps
        working-directory: numbas

  check_rumbas_support_derive:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            numbas/target
            rumbas/target
            rumbas_support/target
            rumbas_support_derive/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --verbose
        working-directory: rumbas_support_derive
      - name: Run tests
        run: cargo test --verbose
        working-directory: rumbas_support_derive
      - name: Run doc
        run: cargo doc --no-deps
        working-directory: rumbas_support_derive
  check_rumbas:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            numbas/target
            rumbas/target
            rumbas_support/target
            rumbas_support_derive/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --verbose
        working-directory: rumbas
      - name: Run tests
        run: cargo test --verbose
        working-directory: rumbas
      - name: Run doc
        run: cargo doc --no-deps
        working-directory: rumbas
  check_cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            numbas/target
            rumbas/target
            rumbas_support/target
            rumbas_support_derive/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install minifyers
        run: |-
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt update && sudo apt install yarn
          yarn global add uglify-js
          yarn global add uglifycss
      - name: Install rumbas
        run: cargo install --path .
        working-directory: rumbas
      - name: Clone Numbas & extensions
        run: |-
          git clone https://github.com/numbas/Numbas.git ~/NUMBAS
          mkdir ~/NUMBAS/extensions
          git clone https://github.com/numbas/numbas-extension-jsxgraph.git ~/NUMBAS/extensions/jsxgraph
          git clone https://github.com/numbas/numbas-extension-stats.git ~/NUMBAS/extensions/stats
          git clone https://github.com/numbas/numbas-extension-eukleides.git ~/NUMBAS/extensions/eukleides
          git clone https://github.com/numbas/numbas-extension-geogebra.git ~/NUMBAS/extensions/geogebra # TODO: build the right js files?
          git clone https://github.com/jhoobergs/numbas-extension-random-person.git ~/NUMBAS/extensions/random_person 
          git clone https://github.com/numbas/numbas-extension-download-a-text-file.git ~/NUMBAS/extensions/download-text-file 
          git clone https://github.com/numbas/numbas-extension-codewords.git ~/NUMBAS/extensions/codewords 
          git clone https://github.com/numbas/numbas-extension-permutations.git ~/NUMBAS/extensions/permutations 
          git clone https://github.com/numbas/numbas-extension-quantities.git ~/NUMBAS/extensions/quantities 
          git clone https://github.com/numbas/numbas-extension-optimisation.git ~/NUMBAS/extensions/optimisation 
          git clone https://github.com/numbas/numbas-extension-polynomials.git ~/NUMBAS/extensions/polynomials 
          git clone https://github.com/numbas/numbas-extension-chemistry.git ~/NUMBAS/extensions/chemistry 
          git clone https://github.com/numbas/numbas-extension-linearalgebra.git ~/NUMBAS/extensions/linear-algebra 
          cp -r extensions/written_number ~/NUMBAS/extensions/written-number
          cp -r extensions/graphs ~/NUMBAS/extensions/graphs
          cd ~/NUMBAS && pip install -r requirements.txt
          cd ~/NUMBAS/extensions/random_person && git checkout prefix_compression
      - name: Run cli-tests
        run: |-
          export NUMBAS_FOLDER=~/NUMBAS
          ./test.sh
        working-directory: cli-tests
  check_todos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            numbas/target
            rumbas/target
            rumbas_support/target
            rumbas_support_derive/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Add nightly
        run: |-
          rustup install nightly
          rustup +nightly component add rustfmt
        working-directory: rumbas
      - name: Check todo's
        run: cargo +nightly fmt --all -- --check
        working-directory: rumbas
        continue-on-error: true
